[tool.qpro]
[[tool.qpro.server_targets]]
user = ""
host = ""
path = ""
port = "22"

[tool.qpro.config]
build = "scalac main.scala -d dist/"
entry_point = "main.scala"
executable = "scala -classpath dist QproScalaTemplate"
input_file = "dist/input.txt"
template_root = "template/"
